collections: 
  sections:
    order:
      - projects.html
      - tech.md
      - languages.md
      - travel.md
      - music.md
      - people.md
      - books.md
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"
