collections: 
  art:
    output: true
    permalink: /gallery/:name
  models:
    output: true
    permalink: /:collection/:name
  fragments:
  sections:
    order:
      - writing.html
      - projects.html
      - in-progress.html
      - tech.md
      - languages.md
      - art.md
      - models.html
      - travel.md
      - music.html
      - people.md
      - books.md
      - fragments.html
      - around.md
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-timeago

kramdown:
  hard_wrap: true

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "art" 
    values:
      layout: "art"
  -
    scope:
      path: ""
      type: "models" 
    values:
      layout: "model"
permalink: /:slug

# Sitewide variables
art_dir: /assets/art/
art_thumbnails_dir: /assets/art/thumbnails/
img_dir: /assets/img/

github: https://github.com/pooriar
twitter: https://twitter.com/pooria_r
email: mailto:pooria@hey.com
