collections: 
  art:
    output: true
    permalink: /:collection/:name
  moments:
  sections:
    order:
      - writing.html
      - projects.html
      - tech.md
      - languages.md
      - art.md
      - travel.md
      - music.md
      - moments.md
      - people.md
      - books.md
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-timeago

kramdown:
  hard_wrap: true

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "art" 
    values:
      layout: "art"

permalink: /:slug
